MODEL_OPTIONS = ("tiny", "base", "small", "medium", "large-v2", "large-v3")
COMPUTE_OPTIONS = ("int8", "int8_float16", "float16", "float32")
MEMORY_PROFILE_OPTIONS = ("low", "balanced", "high")
QUALITY_PRESET_OPTIONS = ("rapida", "equilibrada", "alta", "personalizado")
EXPORT_FORMAT_OPTIONS = ("txt", "srt", "vtt", "json")
